config/routes.rb
Hirerankings::Application.routes.draw do

  resources :search_suggestions

  resources :questions

  resources :companies do
    resources :followups
    resources :interviews
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root 'companies#index'

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    company = Company.find(params[:company_id])
    @interviews = company.interviews
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @company = Company.find_by_id(params[:company_id])
    @interview = @company.interviews.build
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @company = Company.find_by_id(params[:company_id])
    @interview = @company.interviews.create(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to [@interview.company, @interview], notice: 'Interview was successfully created.'}
        format.json { render action: 'show', status: :created, location: [@interview.company, @interview] }
      else
        format.html { render action: 'new' }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:question_id, :company_id)
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_for([@interview.company, @interview]) do |f| %>
  <% if @interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% @interview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :question_id, Question.all.collect { |q| [q.body, q.id] } %><br>
  </div>
  <div class="field">
    <br>
    <%= f.select :company_id, Company.all.collect{ |c| [c.name, c.id] }%>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<h1>Listing interviews</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Company</th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.question.body %></td>
        <td><%= interview.company.name %></td>
        <td><%#= link_to 'Show', company_path(@company) %></td>
        <td><%#= link_to 'Edit', edit_company_interview_path(interview) %></td>
        <td><%#= link_to 'Destroy', company_interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

<%= link_to 'New Question', new_question_path %>

app/views/interviews/new.html.erb
<h3>Add a New Question</h3>

<p>Choose from an existing question:</p>

<%= render 'form' %>

<%= link_to 'Back', company_path(@company) %>
<hr/>
<h3>Can't find your question?</h3>

    <h3><%= link_to ' Click Here!', new_question_path, id: "new_link", remote: true %></h3>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @interview.question.body %>
</p>

<p>
  <strong>Company:</strong>
  <%= @interview.company.name %>
</p>

<%= link_to 'Back', company_interviews_path %>