config/routes.rb
Hirerankings::Application.routes.draw do

  resources :search_suggestions

  resources :questions

  resources :companies do
    resources :followups
    resources :interviews
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :interviews
  has_many :questions, through: :interviews
  has_many :followups
  accepts_nested_attributes_for :questions

  mount_uploader :logo, LogoUploader

  searchable do
    text :name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @search = Company.search do
      fulltext params[:search]
    end
    @companies = @search.results
    #binding.pry
    #@interviews = Interview.where(:company_id == company.id)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    #authorize @company
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    #authorize @company
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :city, :state, :logo)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.file_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="row">
  <br/>

<%= form_tag companies_path, :method => :get do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>

  <% @companies.each do |company| %>
    <h1><%= link_to company.name, company_path(company) %></h1>
    <h3><%= company.city %>,
        <%= company.state %></h3>

<hr/>

  <% end %>

</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= image_tag @company.logo, :size => "200x200" %>
  <%= @company.name %>
</h2>

<hr/>
 <h4>Interview questions provided by users: </h4>
  <br>

<table>
  <thead>
    <tr>
      <th>Category:</th>
      <th>Question:</th>
      </tr>
  </thead>

  <tbody>
    <% @company.questions.each do |q| %>
      <tr>
        <td><%= q.category %></td>
        <td><%= q.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>

<p> Have you interviewed with <%= @company.name %>?
      <%= link_to 'Click Here', new_company_interview_path(@company) %> to add question(s).</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>