config/routes.rb
Hirerankings::Application.routes.draw do

  resources :search_suggestions

  resources :questions

  resources :companies do
    resources :followups
    resources :interviews
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root 'companies#index'

end

app/models/followup.rb
class Followup < ActiveRecord::Base
  belongs_to :company
end

app/controllers/followups_controller.rb
class FollowupsController < ApplicationController
  before_action :set_followup, only: [:show, :edit, :update, :destroy]

  # GET /followups
  # GET /followups.json
  def index
    @followups = Followup.all
  end

  # GET /followups/1
  # GET /followups/1.json
  def show
  end

  # GET /followups/new
  def new
    @followup = Followup.new
  end

  # GET /followups/1/edit
  def edit
  end

  # POST /followups
  # POST /followups.json
  def create
    @followup = Followup.new(followup_params)
    authorize @followup
    respond_to do |format|
      if @followup.save
        format.html { redirect_to @followup, notice: 'Followup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @followup }
      else
        format.html { render action: 'new' }
        format.json { render json: @followup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followups/1
  # PATCH/PUT /followups/1.json
  def update
    respond_to do |format|
      if @followup.update(followup_params)
        format.html { redirect_to @followup, notice: 'Followup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @followup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followups/1
  # DELETE /followups/1.json
  def destroy
    authorize @followup
    @followup.destroy

    respond_to do |format|
      format.html { redirect_to followups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_followup
      @followup = Followup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def followup_params
      params.require(:followup).permit(:reply, :offer)
    end
end

app/helpers/followups_helper.rb
module FollowupsHelper
end

app/views/followups/_form.html.erb
<%= form_for(@followup) do |f| %>
  <% if @followup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@followup.errors.count, "error") %> prohibited this followup from being saved:</h2>

      <ul>
      <% @followup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reply %><br>
    <%= f.number_field :reply %>
  </div>
  <div class="field">
    <%= f.label :offer %><br>
    <%= f.check_box :offer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followups/edit.html.erb
<h1>Editing followup</h1>

<%= render 'form' %>

<%= link_to 'Show', @followup %> |
<%= link_to 'Back', followups_path %>

app/views/followups/index.html.erb
<h1>Listing followups</h1>

<table>
  <thead>
    <tr>
      <th>Reply</th>
      <th>Offer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @followups.each do |followup| %>
      <tr>
        <td><%= followup.reply %></td>
        <td><%= followup.offer %></td>
        <td><%= link_to 'Show', followup %></td>
        <td><%= link_to 'Edit', edit_followup_path(followup) %></td>
        <td><%= link_to 'Destroy', followup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Followup', new_followup_path %>

app/views/followups/new.html.erb
<h1>New followup</h1>

<%= render 'form' %>

<%= link_to 'Back', followups_path %>

app/views/followups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reply:</strong>
  <%= @followup.reply %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @followup.offer %>
</p>

<%= link_to 'Edit', edit_followup_path(@followup) %> |
<%= link_to 'Back', followups_path %>